name: Deploy to Server

on:
  push:
    branches:
      - main  # Replace 'main' with your default branch if it's different

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Create SSH directory
      run: mkdir -p $HOME/.ssh

    - name: Decode SSH Key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" | base64 --decode > $HOME/.ssh/deployment_key
        chmod 600 $HOME/.ssh/deployment_key

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }} # Optional: if you're using a port other than the ssh default of 22
        script: |
          cd /path/to/your/deployment/directory
          git pull origin main
          # Any other deployment steps like restarting services, etc.
